# Generated by Django 3.1.7 on 2021-05-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
